spring:
  application:
    name: hk-sar
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    import: optional:file:env.properties
server:
  port: 8080
  servlet:
    contextPath: /hk-sar-service
