spring:
  application:
    name: hk-sar
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-32277523-ewangclarks-d301.a.aivencloud.com:14763/hk-sar?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ewangclarks
    password: AVNS_3iPrsg-nF_eSPw3A9vb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
  servlet:
    contextPath: /hk-sar-service
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
springdoc:
  show-login-endpoint=true: