spring:
  application:
    name: hk-sar
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hk-sar-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
  servlet:
    contextPath: /hk-sar-service
